// swift-tools-version: 5.10
import PackageDescription

let package = Package(
    name: "ThreadMapper",
    defaultLocalization: "en",
    // iOS only — the sources import HomeKit and UIKit, neither of which exists
    // on macOS. Declaring macOS support here made `swift build` fail with a
    // confusing "no such module 'UIKit'" instead of an honest platform error.
    // The app, widget, and test bundle are built from ThreadMapper.xcodeproj
    // (generated by XcodeGen from project.yml); see the Makefile.
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "ThreadMapper", targets: ["ThreadMapper"]),
    ],
    targets: [
        .target(
            name: "ThreadMapper",
            path: "Sources",
            exclude: ["ThreadMapper/Assets.xcassets",
                      "ThreadMapper/Info.plist",
                      "ThreadMapper/ThreadMapper.entitlements",
                      "ThreadMapper/Localizable.xcstrings"],
            sources: ["ThreadMapper", "Shared"],
            swiftSettings: [.enableExperimentalFeature("StrictConcurrency")]
        ),
        .testTarget(
            name: "ThreadMapperTests",
            dependencies: ["ThreadMapper"],
            swiftSettings: [.enableExperimentalFeature("StrictConcurrency")]
        ),
    ]
)
